version: "3.7"
services:
  postgres:
    image: postgres:14.2-alpine
    container_name: naptime-postgres
    volumes:
      - ./docker/data/pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: naptime
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - interleaved

volumes:
  pgdata:

networks:
  interleaved:
